### ISSUE TITLE
Unable to resolve '~'

### ISSUE THREAD

**Issue by justindra** [CollectionFS/Meteor-cfs-filesystem#13]
Hi, I've created my FS Store using the example.

```javascript
var Images = new FS.Collection("images", {
  stores: [new FS.Store.FileSystem("images", {path: "~/uploads"})]
});
```
But I am receiving this error when I deploy to meteor.
```
FS.Store.FileSystem unable to resolve "~" in path
```
Just wondering if there is a way to fix this.

Thanks!

**Comment by aldeed** [comment]
What operating system?

**Comment by justindra** [comment]
I am on elementaryOS. I'm not sure what the meteor servers are running.

**Comment by aldeed** [comment]
Oh, I didn't read the "when I deploy to meteor" part. The Meteor servers (and probably all hosting servers) don't give you access to the user directory. In general, you should not use filesystem storage adapter with hosting that isn't your own server. In some cases, like with Modulus hosting, there is a cloud directory path they give you that you could use with filesystem SA. Otherwise use GridFS or S3.

**Comment by justindra** [comment]
Ok, thank you very much!
